import { Card, CardHeader, PageHeader, SourceTag } from "@/components/ui";

const PRINCIPLES = [
  {
    title: "Privacy by design",
    body: "All data is synthetic, generated by a seeded generator. No names, phone numbers, national IDs, account numbers or customer records exist anywhere in the system; agent coordinates are random points around district centroids. Automated tests assert the absence of PII-like fields.",
  },
  {
    title: "Explainability",
    body: "Every risk score is the sum of five bounded, documented components. 'Why this risk?' statements are generated from calculated evidence (forecast, coverage, shortfall, velocity, history, calendar context) — not from a free-form language model. Model-level drivers are shown via permutation importance.",
  },
  {
    title: "Human oversight",
    body: "Rebalancing is a recommendation. A reviewer must open the evidence, acknowledge it, and click 'Approve Simulation'. Approval only runs a what-if simulation and writes an audit-log entry. AgentFlow never sends a payment instruction and never moves money.",
  },
  {
    title: "Safety constraints",
    body: "Donors must be LOW risk, in the same district, within 15 km, and keep at least 110% of their own P90 forecast requirement. Recommended amounts never exceed a donor's safe surplus and never create negative balances (unit-tested). Remaining need is escalated to a human-run distributor process.",
  },
  {
    title: "Anomaly ≠ fraud",
    body: "Behavioural anomaly detection flags unusual activity relative to an agent's own history. It never labels an agent fraudulent and does not change the liquidity risk score. At-risk agents with unusual activity are held for manual review instead of receiving automated support recommendations.",
  },
  {
    title: "Transparency of sources",
    body: "The UI tags each number as ML prediction, deterministic calculation, recommendation, simulation, or synthetic data, so reviewers know what kind of evidence they are looking at.",
  },
  {
    title: "Honest evaluation",
    body: "Models are evaluated on a time-based, purged, held-out period never used for training. ML is compared with naive and seasonal baselines; where a simple rule is competitive (anomaly detection), that is reported. Impact numbers come from a reproducible simulation and are labelled as synthetic, not real-world upay results.",
  },
  {
    title: "Fairness & consistency",
    body: "Without personal attributes, consistency is checked across operational groups (urban core / periphery / rural; low / medium / high volume) for forecast error, alert precision/recall and impact. Lower alert recall for urban-core agents (rare shortages) is disclosed.",
  },
  {
    title: "Security",
    body: "Secrets only via environment variables (.env is git-ignored; .env.example has placeholders). Strict request validation (Pydantic, ID patterns, bounded inputs), configurable CORS, structured errors without stack traces, no user-supplied code execution, and basic security headers on the web app.",
  },
];

const NOT_TRUST = [
  "Under conditions not represented in training data (e.g. Eid, network outages, natural disasters, policy changes).",
  "For agents with less than 7 days of history (features are incomplete).",
  "When an agent shows unusual behavioural activity — review the activity first.",
  "Before validation on real, consented operational data and a supervised pilot.",
];

export default function ResponsibleAiPage() {
  return (
    <>
      <PageHeader title="Responsible AI" subtitle="How AgentFlow keeps humans in control and makes every recommendation explainable, safe and honest." />
      <div className="mb-4 flex flex-wrap gap-2">
        <SourceTag kind="model" />
        <SourceTag kind="calc" />
        <SourceTag kind="rec" />
        <SourceTag kind="sim" />
        <SourceTag kind="data" />
      </div>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
        {PRINCIPLES.map((p) => (
          <Card key={p.title} className="p-5">
            <h3 className="text-sm font-semibold text-slate-900">{p.title}</h3>
            <p className="mt-2 text-sm leading-relaxed text-slate-600">{p.body}</p>
          </Card>
        ))}
      </div>
      <Card className="mt-4">
        <CardHeader title="When not to trust AgentFlow blindly" />
        <ul className="list-disc space-y-1.5 py-4 pl-10 pr-5 text-sm text-slate-700">
          {NOT_TRUST.map((t) => (
            <li key={t}>{t}</li>
          ))}
        </ul>
      </Card>
      <p className="mt-4 text-xs text-slate-500">
        Full details: docs/MODEL_CARD.md, docs/DATA_CARD.md and docs/EVALUATION.md in the repository. Synthetic data for hackathon prototyping — not production upay data.
      </p>
    </>
  );
}
